//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeekStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeekStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boot {
            get {
                object obj = ResourceManager.GetObject("boot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap build {
            get {
                object obj = ResourceManager.GetObject("build", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to == Changelog for MeekStudio ==
        ///
        ///[1.1.1.0]
        ///- Add decompile view for DSC
        ///
        ///[1.1.0.1]
        ///- Fix crash when typing in a const directive
        ///- Fix #bintime filter
        ///
        ///[1.1.0.0]
        ///- Add icons and toolbar
        ///- Add support for PV_BRANCH_MODE when using timeblock sorting
        ///- Add support for inputting time in other formats, such as MM:ss.ms or F(Frame) or ss.ms
        ///- Add new precompiler directives: &quot;#for VARNAME start end step ...&quot; and &quot;#endfor&quot;
        ///- Allow inputting booleans as 1 or 0
        ///
        ///[1.0.1.0]
        ///- Fix a bug where decimal poin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon code {
            get {
                object obj = ResourceManager.GetObject("code", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon dir {
            get {
                object obj = ResourceManager.GetObject("dir", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon dsc {
            get {
                object obj = ResourceManager.GetObject("dsc", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pv_999.bpm=100
        ///pv_999.date=20120927
        ///pv_999.difficulty.attribute.original=1
        ///pv_999.difficulty.easy.length=0
        ///pv_999.difficulty.encore.length=0
        ///pv_999.difficulty.extreme.length=0
        ///pv_999.difficulty.hard.length=0
        ///pv_999.difficulty.normal.0.edition=0
        ///pv_999.difficulty.normal.0.level=PV_LV_01_0
        ///pv_999.difficulty.normal.0.level_sort_index=0
        ///pv_999.difficulty.normal.0.script_file_name=rom/script/pv_999_normal.dsc
        ///pv_999.difficulty.normal.0.script_format=0x14012316
        ///pv_999.difficulty.normal.0.version=0
        ///pv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dummy_pv_db_txt {
            get {
                return ResourceManager.GetString("dummy_pv_db.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gm_pv_list_tbl_pv900 {
            get {
                object obj = ResourceManager.GetObject("gm_pv_list_tbl_pv900", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loadProj {
            get {
                object obj = ResourceManager.GetObject("loadProj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap meekstudio {
            get {
                object obj = ResourceManager.GetObject("meekstudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newProj {
            get {
                object obj = ResourceManager.GetObject("newProj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newProj1 {
            get {
                object obj = ResourceManager.GetObject("newProj1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Entrypoint file for your project --
        ///// This is the file where the DSC build will start from
        ///// Include all scenes and stuff in here
        ///
        ///PV_BRANCH_MODE 0 // disable, because not yet supported
        ///
        ///
        ///// You can include a file like this
        ///#include scenes/first.mia
        ///#include scenes/second.mia
        ///
        ///
        ///-- Output directives --
        ///// This is an example of how to output multiple charts from same PV
        ///// Replace your PV ID
        ///
        ///#const OUT_PV_ID=XXX
        ///
        ///----- ↓↓↓　Extreme output　↓↓↓ -----
        ///#ctxstart
        ///    // Insert chart data
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_main_tpl_txt {
            get {
                return ResourceManager.GetString("project_main_tpl.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Template file from MeekStudio
        ///
        ///pv_420.bpm=100
        ///pv_420.date=20120927
        ///pv_420.difficulty.attribute.original=1
        ///pv_420.difficulty.easy.0.edition=0
        ///pv_420.difficulty.easy.0.level=PV_LV_08_5
        ///pv_420.difficulty.easy.0.level_sort_index=0
        ///pv_420.difficulty.easy.0.script_file_name=rom/script/pv_420_normal.dsc
        ///pv_420.difficulty.easy.0.script_format=0x14012316
        ///pv_420.difficulty.easy.0.version=1
        ///pv_420.difficulty.easy.length=1
        ///pv_420.difficulty.encore.length=0
        ///pv_420.difficulty.extreme.length=0
        ///pv_420.diffi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pv_db_entry_txt {
            get {
                return ResourceManager.GetString("pv_db_entry.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pvdb {
            get {
                object obj = ResourceManager.GetObject("pvdb", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveAll {
            get {
                object obj = ResourceManager.GetObject("saveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon sound {
            get {
                object obj = ResourceManager.GetObject("sound", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
