//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MikuASM.Common.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MikuASM.Common.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary import filtering is now {0}.
        /// </summary>
        internal static string BinFltSts {
            get {
                return ResourceManager.GetString("BinFltSts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared output buffer.
        /// </summary>
        internal static string ClrBuf {
            get {
                return ResourceManager.GetString("ClrBuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined {0}={1}.
        /// </summary>
        internal static string ConstDef {
            get {
                return ResourceManager.GetString("ConstDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined {0}.
        /// </summary>
        internal static string ConstUndef {
            get {
                return ResourceManager.GetString("ConstUndef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned to context {0}.
        /// </summary>
        internal static string CtxPop {
            get {
                return ResourceManager.GetString("CtxPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushed into context {0}.
        /// </summary>
        internal static string CtxPush {
            get {
                return ResourceManager.GetString("CtxPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: emitted {1} from {2}.
        /// </summary>
        internal static string Emit {
            get {
                return ResourceManager.GetString("Emit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument count mismatched..
        /// </summary>
        internal static string ErrArgCount {
            get {
                return ResourceManager.GetString("ErrArgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough arguments: expected {0}, but have {1}.
        /// </summary>
        internal static string ErrArgCountLen {
            get {
                return ResourceManager.GetString("ErrArgCountLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using more than 3 branches does not look valid..
        /// </summary>
        internal static string ErrBranchCount {
            get {
                return ResourceManager.GetString("ErrBranchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command {0}.
        /// </summary>
        internal static string ErrCmdNotFound {
            get {
                return ResourceManager.GetString("ErrCmdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect const syntax.
        /// </summary>
        internal static string ErrConstSyntax {
            get {
                return ResourceManager.GetString("ErrConstSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: #const name=value.
        /// </summary>
        internal static string ErrConstSyntaxDetail {
            get {
                return ResourceManager.GetString("ErrConstSyntaxDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect argument count for {0}.
        /// </summary>
        internal static string ErrForArgs {
            get {
                return ResourceManager.GetString("ErrForArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify args in sets of VARNAME START END STEP.
        /// </summary>
        internal static string ErrForArgsDetail {
            get {
                return ResourceManager.GetString("ErrForArgsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection failed.
        /// </summary>
        internal static string ErrInjectionFail {
            get {
                return ResourceManager.GetString("ErrInjectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot undefine a keyword.
        /// </summary>
        internal static string ErrKwUndef {
            get {
                return ResourceManager.GetString("ErrKwUndef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no common branch commands in the script..
        /// </summary>
        internal static string ErrNoCommonCmd {
            get {
                return ResourceManager.GetString("ErrNoCommonCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist!.
        /// </summary>
        internal static string ErrNotExist {
            get {
                return ResourceManager.GetString("ErrNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name ambiguous: {0}.
        /// </summary>
        internal static string ErrProcAmbiguous {
            get {
                return ResourceManager.GetString("ErrProcAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process not found: {0}.
        /// </summary>
        internal static string ErrProcNotFound {
            get {
                return ResourceManager.GetString("ErrProcNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote alloc failed: 0x{0:X}.
        /// </summary>
        internal static string ErrRallocFail {
            get {
                return ResourceManager.GetString("ErrRallocFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already defined..
        /// </summary>
        internal static string ErrRedef {
            get {
                return ResourceManager.GetString("ErrRedef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote thread creation failed: 0x{0:X} (thread result 0x{0:X}).
        /// </summary>
        internal static string ErrRthreadFail {
            get {
                return ResourceManager.GetString("ErrRthreadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote write failed: 0x{0:X}.
        /// </summary>
        internal static string ErrRwriteFail {
            get {
                return ResourceManager.GetString("ErrRwriteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No open context to close..
        /// </summary>
        internal static string ErrTopCtx {
            get {
                return ResourceManager.GetString("ErrTopCtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a context with #ctxstart prior to closing it..
        /// </summary>
        internal static string ErrTopCtxDetail {
            get {
                return ResourceManager.GetString("ErrTopCtxDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected {0}.
        /// </summary>
        internal static string ErrUnexpected {
            get {
                return ResourceManager.GetString("ErrUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command or identifier unknown..
        /// </summary>
        internal static string ErrUnknownCmd {
            get {
                return ResourceManager.GetString("ErrUnknownCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid preprocessor directive..
        /// </summary>
        internal static string ErrUnknownPrepro {
            get {
                return ResourceManager.GetString("ErrUnknownPrepro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an unko..
        /// </summary>
        internal static string ErrUnko {
            get {
                return ResourceManager.GetString("ErrUnko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unko!.
        /// </summary>
        internal static string ForceStop {
            get {
                return ResourceManager.GetString("ForceStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got handle {0}.
        /// </summary>
        internal static string GotHandle {
            get {
                return ResourceManager.GetString("GotHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} commands from binary {1}.
        /// </summary>
        internal static string IncBin {
            get {
                return ResourceManager.GetString("IncBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading {0}.
        /// </summary>
        internal static string Including {
            get {
                return ResourceManager.GetString("Including", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite sequence definition for {0}.
        /// </summary>
        internal static string InfForLoop {
            get {
                return ResourceManager.GetString("InfForLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence does not converge with the defined range and step values in a finite number of steps..
        /// </summary>
        internal static string InfForLoopDetail {
            get {
                return ResourceManager.GetString("InfForLoopDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This didn&apos;t originate from the MikuASM compiler engine....
        /// </summary>
        internal static string OutsideError {
            get {
                return ResourceManager.GetString("OutsideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code error: 
        ///    {0}.
        /// </summary>
        internal static string PrintSrcError {
            get {
                return ResourceManager.GetString("PrintSrcError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     expanded from: 
        ///        {0}.
        /// </summary>
        internal static string PrintSrcErrorExpand {
            get {
                return ResourceManager.GetString("PrintSrcErrorExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra reference: 
        ///{0}.
        /// </summary>
        internal static string PrintSrcErrorHelp {
            get {
                return ResourceManager.GetString("PrintSrcErrorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     at {0} line {1}: 
        ///        {2}.
        /// </summary>
        internal static string PrintSrcErrorLoc {
            get {
                return ResourceManager.GetString("PrintSrcErrorLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created remote thread {0}.
        /// </summary>
        internal static string RthreadCreate {
            get {
                return ResourceManager.GetString("RthreadCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting timeblocks.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug server injected.
        /// </summary>
        internal static string StsInjected {
            get {
                return ResourceManager.GetString("StsInjected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injecting debug bridge into PID {0} / pHandle {1}....
        /// </summary>
        internal static string StsInjecting {
            get {
                return ResourceManager.GetString("StsInjecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituted: {0} into {1}.
        /// </summary>
        internal static string Subst {
            get {
                return ResourceManager.GetString("Subst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensive logging enabled as per #chatty.
        /// </summary>
        internal static string Verbose {
            get {
                return ResourceManager.GetString("Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing current buffer to {0}.
        /// </summary>
        internal static string WriteBuf {
            get {
                return ResourceManager.GetString("WriteBuf", resourceCulture);
            }
        }
    }
}
