//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeekStudio.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeekStudio.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeekStudio is an integrated environment for writing scripts in MikuASM and compiling/debugging them using certain game software.
        ///
        ///[MeekStudio Credits]
        ///This software uses the ScintillaNET syntax highlighting text editor component by jacobslusser, licensed under the MIT license as of 2020/11/15.
        ///Github link for ScintillaNET: https://github.com/jacobslusser/ScintillaNET
        ///
        ///The icon used in the Welcome dialog and as the application icon was designed by @hatsune_negame: https://twitter.com/hatsune_negame
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate.
        /// </summary>
        internal static string BtnAnimate {
            get {
                return ResourceManager.GetString("BtnAnimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animating....
        /// </summary>
        internal static string BtnAnimating {
            get {
                return ResourceManager.GetString("BtnAnimating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build error.
        /// </summary>
        internal static string BuildErrorTitle {
            get {
                return ResourceManager.GetString("BuildErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to leave project {0}?.
        /// </summary>
        internal static string CloseProjectMsg {
            get {
                return ResourceManager.GetString("CloseProjectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close project.
        /// </summary>
        internal static string CloseProjectTitle {
            get {
                return ResourceManager.GetString("CloseProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during decompilation..
        /// </summary>
        internal static string DecompileError {
            get {
                return ResourceManager.GetString("DecompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompile: {0}.
        /// </summary>
        internal static string DecompileTitle {
            get {
                return ResourceManager.GetString("DecompileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        internal static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This looks like an existing project folder..
        /// </summary>
        internal static string ErrAlreadyProject {
            get {
                return ResourceManager.GetString("ErrAlreadyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build failure..
        /// </summary>
        internal static string ErrBuildFailure {
            get {
                return ResourceManager.GetString("ErrBuildFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game exe is not configured or doesn&apos;t exist.
        /// </summary>
        internal static string ErrGameExeNotFound {
            get {
                return ResourceManager.GetString("ErrGameExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No script editor is active!.
        /// </summary>
        internal static string ErrNoEditor {
            get {
                return ResourceManager.GetString("ErrNoEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project open.
        /// </summary>
        internal static string ErrNoProject {
            get {
                return ResourceManager.GetString("ErrNoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not seem to be a valid project folder..
        /// </summary>
        internal static string ErrNotProject {
            get {
                return ResourceManager.GetString("ErrNotProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not set or does not exist..
        /// </summary>
        internal static string ErrNotSet {
            get {
                return ResourceManager.GetString("ErrNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string FailureTitle {
            get {
                return ResourceManager.GetString("FailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No quick help available..
        /// </summary>
        internal static string HlpNoneAvail {
            get {
                return ResourceManager.GetString("HlpNoneAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file.
        /// </summary>
        internal static string ImportFileTitle {
            get {
                return ResourceManager.GetString("ImportFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file....
        /// </summary>
        internal static string MnuAddFile {
            get {
                return ResourceManager.GetString("MnuAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MnuDelFile {
            get {
                return ResourceManager.GetString("MnuDelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute file.
        /// </summary>
        internal static string MnuEvalFile {
            get {
                return ResourceManager.GetString("MnuEvalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string MnuNewFile {
            get {
                return ResourceManager.GetString("MnuNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string MnuNewFolder {
            get {
                return ResourceManager.GetString("MnuNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVDB.
        /// </summary>
        internal static string MnuPvDb {
            get {
                return ResourceManager.GetString("MnuPvDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up and reorder.
        /// </summary>
        internal static string MnuPvDbCleanUp {
            get {
                return ResourceManager.GetString("MnuPvDbCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string MnuRenFile {
            get {
                return ResourceManager.GetString("MnuRenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as....
        /// </summary>
        internal static string MnuSetAs {
            get {
                return ResourceManager.GetString("MnuSetAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview in progress, end to continue..
        /// </summary>
        internal static string MsgPreviewing {
            get {
                return ResourceManager.GetString("MsgPreviewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the game on song selector screen, then click OK to attach.
        /// </summary>
        internal static string MsgWaitSelector {
            get {
                return ResourceManager.GetString("MsgWaitSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a project folder.
        /// </summary>
        internal static string OpenProjectTitle {
            get {
                return ResourceManager.GetString("OpenProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder for the project to reside in.
        /// </summary>
        internal static string SelectFolderTitle {
            get {
                return ResourceManager.GetString("SelectFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build finished in {0} seconds.
        /// </summary>
        internal static string StsBuildFinish {
            get {
                return ResourceManager.GetString("StsBuildFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build started: {0}.
        /// </summary>
        internal static string StsBuildStart {
            get {
                return ResourceManager.GetString("StsBuildStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set {0}.
        /// </summary>
        internal static string StsCannotChgThing {
            get {
                return ResourceManager.GetString("StsCannotChgThing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0} to {1}.
        /// </summary>
        internal static string StsChangedThing {
            get {
                return ResourceManager.GetString("StsChangedThing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile: {0}.
        /// </summary>
        internal static string StsCompile {
            get {
                return ResourceManager.GetString("StsCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompiled {0} in {1} seconds.
        /// </summary>
        internal static string StsDecompiled {
            get {
                return ResourceManager.GetString("StsDecompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not decompile {0}: {1}.
        /// </summary>
        internal static string StsDecompileError {
            get {
                return ResourceManager.GetString("StsDecompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build: {0}.
        /// </summary>
        internal static string StsEmit {
            get {
                return ResourceManager.GetString("StsEmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated: {0}.
        /// </summary>
        internal static string StsEval {
            get {
                return ResourceManager.GetString("StsEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached to game process.
        /// </summary>
        internal static string StsGameAttached {
            get {
                return ResourceManager.GetString("StsGameAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detached from game process.
        /// </summary>
        internal static string StsGameDetached {
            get {
                return ResourceManager.GetString("StsGameDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not attached!.
        /// </summary>
        internal static string StsGameNotAttached {
            get {
                return ResourceManager.GetString("StsGameNotAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a script!.
        /// </summary>
        internal static string StsNotScript {
            get {
                return ResourceManager.GetString("StsNotScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project unloaded.
        /// </summary>
        internal static string StsProjectClose {
            get {
                return ResourceManager.GetString("StsProjectClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new project {0}.
        /// </summary>
        internal static string StsProjectNew {
            get {
                return ResourceManager.GetString("StsProjectNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded project {0}.
        /// </summary>
        internal static string StsProjectOpen {
            get {
                return ResourceManager.GetString("StsProjectOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaned up PVDB entry file.
        /// </summary>
        internal static string StsPvDbCleanedUp {
            get {
                return ResourceManager.GetString("StsPvDbCleanedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting debug instance.
        /// </summary>
        internal static string StsStartingDebug {
            get {
                return ResourceManager.GetString("StsStartingDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting up preview.
        /// </summary>
        internal static string StsStartingPreview {
            get {
                return ResourceManager.GetString("StsStartingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for application to reattach....
        /// </summary>
        internal static string StsWaitReattach {
            get {
                return ResourceManager.GetString("StsWaitReattach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrypoint script.
        /// </summary>
        internal static string ThingEntrypoint {
            get {
                return ResourceManager.GetString("ThingEntrypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie audio.
        /// </summary>
        internal static string ThingMovieAudio {
            get {
                return ResourceManager.GetString("ThingMovieAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie output.
        /// </summary>
        internal static string ThingMovieDsc {
            get {
                return ResourceManager.GetString("ThingMovieDsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV DB snippet.
        /// </summary>
        internal static string ThingPvDb {
            get {
                return ResourceManager.GetString("ThingPvDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach to game.
        /// </summary>
        internal static string WaitSelectorTitle {
            get {
                return ResourceManager.GetString("WaitSelectorTitle", resourceCulture);
            }
        }
    }
}
